spring:
  application:
    name: authService

  security:
    user:
      name: admin
      password: admin123

  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gomo

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 4004

jwt:
  secret: my-super-secret-jwt-key-which-is-at-least-32-chars


